export { snailDepsContext } from './deps'
export { Snail } from './ui/snail'
export { SnailProvider, useSnailContext } from './ui/snail-provider'
export { StaticSnail } from './ui/static-snail'
export { calculateTargetPosition } from './model/calculate-target-position'
export { useCalcAnimationDuration } from './model/use-animation-duration'
