export const STUN_TIMEOUT = 1600
export const MAX_SPACE_HOLD_TIME = 500
export const CAMERA_MOVE_DURATION = 2500
export const CAMERA_FOCUS_DURATION = 1400
export const COUNTDOWN_DURATION = 3000
export const RACE_LEAD_MARGIN = 1000
export const RACE_LEAD =
  Math.max(CAMERA_MOVE_DURATION, CAMERA_FOCUS_DURATION) + RACE_LEAD_MARGIN
