name: Deploy to Hosting

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master
env:
  SSH_PRIVATE_KEY: ${{ vars.SSH_PRIVATE_KEY }} 
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check if triggered by push or merged PR
        if: |
          github.event_name == 'push' ||
          (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        run: echo "This will run on push to master or merged PR"

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Check if secrets are available
        run: |
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "SSH_PRIVATE_KEY is empty or not set"
          else
            echo "SSH_PRIVATE_KEY is set"
          fi
          
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_KNOWN_HOSTS_CONTENT }}" >> ~/.ssh/known_hosts
          echo "${{ vars.SSH_PRIVATE_KEY }}"
          
      - name: Deploy to Hosting
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "cd snail-rush && git pull origin master && docker compose up --build -d"
