name: Deploy to Hosting

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    if: github.event.pull_request.merged == true    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ vars.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${{ vars.SSH_KNOWN_HOSTS_CONTENT }}" >> ~/.ssh/known_hosts
          
      - name: Deploy to Hosting
        run: |
          ssh ${{ vars.REMOTE_USER }}@${{ vars.REMOTE_HOST }} "cd snail-rush && git pull origin master && sudo docker compose up --build -d"
